---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deploy
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./app/base
  targetNamespace: flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  images:
  - name: arungupta/helloworld-spring-boot
    newTag: update-only-dev-pull-request-d774d9cc20-amd64